apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "biz-app"
  name: "biz-app"
  namespace: pims
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "biz-app"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "biz-app"
    spec:
      containers:
        - image: npimsdevacr.azurecr.io/pims-frontend/apps/biz:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            initialDelaySeconds: 60
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            initialDelaySeconds: 30
          name: "biz-app"
          env:
            - name: "REACT_APP_ENVIRONMENT"
              value: "PROD"
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 1000m
              memory: 2G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "biz-app"
  name: "biz-app"
  namespace: pims
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: "biz-app"
  sessionAffinity: None
